##########################################################################
#AUTOMATE JIT REQUESTS
##########################################################################
#THESE SCRIPTS MUST BE PASTED IN THE AZURE CLOUD SHELL 
#THEO EKELMANS - 2024-07-24 - THEO.EKELMANS@ORDINA.NL

###############################
#REACTIVATE JIT'S
#NOTE: THIS LIST IS SLOW!
###############################
FUNCTION REACTIVATEJIT
{
    PARAM (
        [CMDLETBINDING()]
        [VALIDATENOTNULLOREMPTY()]
        [PARAMETER(MANDATORY=$TRUE)]
        [STRING]$NAMEFILTER
    )

$SERVERLIST = @()
$JITRESULT = @()

WRITE-HOST '##############################################################################' 
WRITE-HOST 'SCANNING ALL SUBSCRIPTIONS/RESOURCEGROUPS FOR VMS WITH JIT' 
WRITE-HOST '##############################################################################' 

WRITE-HOST 'GATHERING INFO FOR: <SUBSCRIPTIONNAME> - <RESOURCEGROUPNAME> - <VMNAME>' 
WRITE-HOST '------------------------------------------------------------------------------' 

$SUBSCRIPTIONS = GET-AZSUBSCRIPTION | WHERE-OBJECT { ($_.NAME -LIKE "$NAMEFILTER" ) } 
FOREACH ($SUBSCRIPTION IN $SUBSCRIPTIONS) {
    $SUBSCRIPTIONNAME = $SUBSCRIPTION.NAME

    SET-AZCONTEXT -SUBSCRIPTIONNAME "$SUBSCRIPTIONNAME" | OUT-NULL
    $RGS = GET-AZRESOURCEGROUP 
        FOREACH ($RG IN $RGS) {

            #GET THE JIT POLICIES FOR THIS RESOURCEGROUP
            $AZJITPOLICIES = GET-AZJITNETWORKACCESSPOLICY -RESOURCEGROUPNAME $RG.RESOURCEGROUPNAME

            # # SHOW THE POLICY DETAILS PER VM FOR THIS RESOURCEGROUP
            # FOREACH ($VMJP IN $AZJITPOLICIES.VIRTUALMACHINES){
            #     $VMJP.ID
            #     $VMJP.PORTS.MAXREQUESTACCESSDURATION
            #     $VMJP.PORTS.NUMBER
            #     $VMJP.PORTS.PROTOCOL
            # }

            #GO THOUGH ALL THE VM'S IN THIS RESOURCEGROUP THAT HAVE A JIT POLICY ATTACHED AND ASSEMBLE THE INFO PER VM 
            $VMS = GET-AZVM -RESOURCEGROUPNAME $RG.RESOURCEGROUPNAME | WHERE-OBJECT {$_.ID -IN $AZJITPOLICIES.VIRTUALMACHINES.ID}
            FOREACH ($VM IN $VMS) {

                $RESOURCEGROUPNAME = $RG.RESOURCEGROUPNAME
                $VMNAME = $VM.NAME

                WRITE-HOST 'GATHERING INFO FOR:'$SUBSCRIPTIONNAME' - '$RESOURCEGROUPNAME' - '$VMNAME

                $VMPRIVATEIP = GET-AZNETWORKINTERFACE `
                | WHERE-OBJECT { $_.VIRTUALMACHINE -AND $_.IPCONFIGURATIONS -AND $_.IPCONFIGURATIONS.PRIVATEIPADDRESS -AND $_.NAME -MATCH "$($VMNAME)*" } `
                | SELECT-OBJECT @{N="PRIVATEIPADDRESS"; E= { $_.IPCONFIGURATIONS.PRIVATEIPADDRESS }}

                # VM STATUS (RUNNING/DEALLOCATED/STOPPED)
                $VMDETAIL = GET-AZVM -RESOURCEGROUPNAME $RG.RESOURCEGROUPNAME -NAME $VM.NAME -STATUS
                $VMSTATUSDETAIL = $VMDETAIL.STATUSES.DISPLAYSTATUS -MATCH "^VM .*$"
                
                $ITEM = NEW-OBJECT PSOBJECT
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "SUBSCRIPTION" -VALUE $SUBSCRIPTIONNAME
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "RESOURCEGROUP" -VALUE $RG.RESOURCEGROUPNAME
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "VMNAME" -VALUE $VM.NAME
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "VMSIZE" -VALUE $VM.HARDWAREPROFILE.VMSIZE  
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "VMSTATUS" -VALUE "$VMSTATUSDETAIL"
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "OSTYPE" -VALUE $VM.STORAGEPROFILE.OSDISK.OSTYPE
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "OSVERSION" -VALUE $VM.STORAGEPROFILE.IMAGEREFERENCE.SKU
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "AVAILABILITYZONE" -VALUE $VM.ZONES[0]
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "PRIVATEIP" -VALUE $VMPRIVATEIP.PRIVATEIPADDRESS
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "JITNAME" -VALUE $AZJITPOLICIES.NAME
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "DURATION" -VALUE ($AZJITPOLICIES.VIRTUALMACHINES | WHERE-OBJECT {$_.ID -EQ $VM.ID}).PORTS.MAXREQUESTACCESSDURATION
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "PORT" -VALUE ($AZJITPOLICIES.VIRTUALMACHINES | WHERE-OBJECT {$_.ID -EQ $VM.ID}).PORTS.NUMBER
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "PROTOCOL" -VALUE ($AZJITPOLICIES.VIRTUALMACHINES | WHERE-OBJECT {$_.ID -EQ $VM.ID}).PORTS.PROTOCOL
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "PREFIX" -VALUE ($AZJITPOLICIES.VIRTUALMACHINES | WHERE-OBJECT {$_.ID -EQ $VM.ID}).PORTS.ALLOWEDSOURCEADDRESSPREFIX
                $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "VMID" -VALUE $VM.ID
                
                $SERVERLIST += $ITEM

           }
        }   
    }

# $SERVERLIST | FORMAT-TABLE SUBSCRIPTION,RESOURCEGROUP,VMNAME,VMSIZE,VMSTATUS,AVAILABILITYZONE,JITNAME,DURATION,PRIVATEIP,PORT,PROTOCOL -FORCE

WRITE-HOST '------------------------------------------------------------------------------' 
WRITE-HOST 'REQUESTING JIT ACCESS FOR: <SUBSCRIPTIONNAME> - <VMNAME>'
WRITE-HOST '------------------------------------------------------------------------------' 

FOREACH($SERVER IN $SERVERLIST){

    $SUBSCRIPTIONNAME = $SERVER.SUBSCRIPTION
    $AZUREVMNAME = $SERVER.VMNAME

    WRITE-HOST 'REQUESTING JIT ACCESS FOR:'$($SUBSCRIPTIONNAME)'-'$($AZUREVMNAME) 

    $AZSUBSCRIPTION = SELECT-AZSUBSCRIPTION -SUBSCRIPTION (GET-AZSUBSCRIPTION | WHERE-OBJECT {$_.NAME -MATCH $SUBSCRIPTIONNAME} ) 
    $VM = GET-AZVM -NAME $AZUREVMNAME
    $IPPREFIX = $SERVER.PREFIX
    
    $JITPOLICY = (@{
            ID    = $VM.ID; 
            PORTS = (@{
                    NUMBER                     = $SERVER.PORT
                    ENDTIMEUTC                 = GET-DATE (GET-DATE -ASUTC).ADDHOURS(1) -FORMAT O #TODO: EXTRACT THIS FROM PT1H
                    ALLOWEDSOURCEADDRESSPREFIX = @($IPPREFIX) 
                })
        })
    $ACTIVATIONVM = @($JITPOLICY)
    $RESULT = START-AZJITNETWORKACCESSPOLICY -RESOURCEGROUPNAME $($VM.RESOURCEGROUPNAME) -LOCATION $VM.LOCATION -NAME "DEFAULT" -VIRTUALMACHINE $ACTIVATIONVM

    $ITEM = NEW-OBJECT PSOBJECT
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "SUBSCRIPTION" -VALUE $SERVER.SUBSCRIPTION
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "RESOURCEGROUP" -VALUE $SERVER.RESOURCEGROUP
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "VMNAME" -VALUE $SERVER.VMNAME
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "VMSIZE" -VALUE $SERVER.VMSIZE
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "VMSTATUS" -VALUE $SERVER.VMSTATUS
    #$ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "OSTYPE" -VALUE $SERVER.OSTYPE
    #$ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "OSVERSION" -VALUE $SERVER.OSVERSION
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "AZ" -VALUE $SERVER.AVAILABILITYZONE
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "PRIVATEIP" -VALUE $SERVER.PRIVATEIP
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "JITNAME" -VALUE $SERVER.JITNAME
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "DURATION" -VALUE $SERVER.DURATION
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "PORT" -VALUE $SERVER.PORT
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "PROTOCOL" -VALUE $SERVER.PROTOCOL
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "PREFIX" -VALUE $SERVER.PREFIX
    #$ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "VMID" -VALUE $SERVER.VMID
    $ITEM |ADD-MEMBER -TYPE NOTEPROPERTY -NAME "STARTDT" -VALUE (GET-DATE ([SYSTEM.TIMEZONEINFO]::CONVERTTIMEBYSYSTEMTIMEZONEID( ($RESULT.STARTTIMEUTC), 'Central European Standard Time')) -FORMAT 'YYYY-MM-DD HH:MM:SS' )
    
    $JITRESULT += $ITEM

}
WRITE-HOST '------------------------------------------------------------------------------' 
WRITE-HOST 'DONE, RESULT BELOW'
WRITE-HOST '------------------------------------------------------------------------------' 
$JITRESULT | FORMAT-TABLE * -FORCE

}

##########################################################################
# CHOOSE YOUR VARIABLES BELOW, AND THEN PASTE EVERYTING INTO A CLOUDSHELL
##########################################################################

#$NAMEFILTER = '*RISKF*' # RISKFACTOR ONLY
$NAMEFILTER = '*AQ*'  # AQAURIUS ONLY
#$NAMEFILTER = '*'  # EVERYTHING

REACTIVATEJIT $NAMEFILTER

